filebeat.inputs:
- type: docker
  containers.ids:
    - '*'  # collect logs from all containers
processors:
- add_docker_metadata: {}
- decode_json_fields:
    fields: ["message"]
    target: ""
    overwrite_keys: true
setup.kibana:
  host: "kibana:5601"
setup.template.name: "todo-app"
setup.template.pattern: "todo-app-*"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "todo-app-%{+yyyy.MM.dd}"
setup.ilm.enabled: false
